parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(CHARSET): 'utf8mb3'
    env(COLLATE): 'utf8_general_ci'
    env(REDIS_URL): 'redis://redis'
    env(REDIS_MESSAGE_URL): 'redis://redis'
    env(FAKER_LOCALE): 'en_GB'
    charset: '%env(CHARSET)%'
    collate: '%env(COLLATE)%'
    faker_locale: '%env(FAKER_LOCALE)%'
    env(MYSQL_ATTR_INIT_COMMAND): "SET NAMES '%charset%' COLLATE '%collate%'"
    redis_url: '%env(REDIS_URL)%'
    redis_message_url: '%env(REDIS_MESSAGE_URL)%'


doctrine:
    dbal:
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            enum:       Doctrine\DBAL\Types\StringType
        default_connection: source
        connections:
            source:
                server_version: '5.7'
                schema_filter: ~^(?!(sfdc_all_accounts|tmp_analytics_a|tmp_analytics_b|tmp_analytics_c|tmp_analytics_d|tmp_analytics_e|tmp_analytics_g|tmp_analytics_h|tmp_analytics_i|tmp_analytics_j|tmp_analytics_k|tmp_analytics_l|tmp_analytics_m|tmp_analytics_n|tmp_analytics_o|tmp_analytics_p|tmp_analytics_q|tmp_analytics_r|tmp_analytics_s|tmp_analytics_t|tmp_analytics_u|tmp_analytics_v|tmp_analytics_w|tmp_analytics_x|tmp_analytics_y|tmp_analytics_z))~
                mapping_types:
                    enum: string
                url: '%env(resolve:SOURCE_DATABASE_URL)%'
                options:
                    !php/const PDO::MYSQL_ATTR_USE_BUFFERED_QUERY: 0
                    charset: '%env(resolve:CHARSET)%'
                    collate: '%env(resolve:COLLATE)%'
                    !php/const PDO::MYSQL_ATTR_INIT_COMMAND: '%env(resolve:MYSQL_ATTR_INIT_COMMAND)%'
            target:
                server_version: '5.7'
                mapping_types:
                    enum: string
                options:
                    !php/const PDO::MYSQL_ATTR_LOCAL_INFILE: 1
                    charset: '%env(resolve:CHARSET)%'
                    collate: '%env(resolve:COLLATE)%'
                    !php/const PDO::MYSQL_ATTR_INIT_COMMAND: '%env(resolve:MYSQL_ATTR_INIT_COMMAND)%'
                url: '%env(resolve:TARGET_DATABASE_URL)%'
