version: '2.0'
services:
  app:
    depends_on:
    - redis
    - target
    - source
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger

  worker:
    depends_on:
    - redis
    - target
    - source
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger

    restart: always
    command: fogger:consumer
  redis:
    image: redis:4
  source:
    environment:
      MYSQL_DATABASE: source
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
    image: mysql:5.7
    volumes:
    - ./var/:/fogger
  target:
    environment:
      MYSQL_DATABASE: target
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
    image: mysql:5.7
